### ISSUE TITLE
CustomDropdown.entries

### ISSUE THREAD

**Issue by CroniD** [leanix/leanix-reporting#3] opened 2017-07-21 15:27 UTC
Hi there,

CustomDropdown.entries doesn't allow an empty array, null or undefined, which leads to an error.

Expected: it should handle an empty array, null and undefined without any errors.

Best regards

**Comment by psurrey** [comment] 2017-08-02 07:44
Hi @CroniD ,

thank you for creating this bug report.
The issue is within the reporting framework in LeanIX itself and will be fixed with the next release.

Best regards

**Closed by psurrey** 2017-08-02 07:44 UTC
Labels: bug
